data_directory: .
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: True
fail_on_overwrite: True

# read:
# - where:
#     quantity: human/mixing-matrix
#   use:
#     filename: human/mixing-matrix/mymixingmatrix.csv

write:
- where:
    {}
  use:
    source: simple_network_sim
