package:
  name: data_pipeline_api
  version: 0.0.1

source:
  path: ..

build:
  noarch: python

requirements:
  build:
    - python
    - PyYaml

  run:
    - python=3.7
    - h5py>=2.9.0
    - toml>=0.9.4
    - scipy>=1.4.1
    - pandas>=1.0.3

test:
  imports:
    - data_pipeline_api

about:
  home: https://github.com/ScottishCovidResponse/data_pipeline_api
