name: ci-cppbindings

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        # This doesn't work:
        # /bin/bash --noprofile --norc -e -o pipefail -o nounset {0}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y python3-setuptools && sudo rm -rf /var/lib/apt/lists/*

    - name: Install Python packages
      run: |
        pip3 install wheel
        pip3 install pybind11 pyyaml pandas scipy toml semver

    - name: Compile
      run: |
        cd bindings/cpp
        make -j 4 build/test_cpp_datapipeline

    - name: Run tests
      run: |
        cd bindings/cpp
        ./build/test_cpp_datapipeline
